AWSTemplateFormatVersion: '2010-09-09'
Description: Backend stack for visitor counter - ongoing management

Parameters:
  AllowedOrigin:
    Type: String
    Default: https://www.theprojectfolder.com
    Description: Allowed CORS origin for the Lambda function

Resources:
  # Manage existing DynamoDB Table
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: VisitorCountTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: visitor_count_id
          AttributeType: S
      KeySchema:
        - AttributeName: visitor_count_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: theprojectfolder
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Environment
          Value: prod

  # Manage existing Lambda Execution Role
  VisitorCounterLambdaRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: visitCounterRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt VisitorCountTable.Arn
      Tags:
        - Key: Project
          Value: theprojectfolder
        - Key: ManagedBy
          Value: CloudFormation

  # Manage existing Lambda Function
  VisitorCounterFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: VisitorCounter
      Runtime: python3.13
      Handler: visitor_counter.lambda_handler
      Role: !GetAtt VisitorCounterLambdaRole.Arn
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref AllowedOrigin
          DYNAMODB_TABLE: !Ref VisitorCountTable
      Code:
        ZipFile: |
          # This is placeholder code in the template
          # The actual code will be deployed via the CI/CD workflow
          # using the 'aws lambda update-function-code' command
          import json
          import boto3
          import os
          from datetime import datetime

          dynamodb = boto3.resource('dynamodb')
          table_name = os.environ.get('DYNAMODB_TABLE', 'VisitorCountTable')
          table = dynamodb.Table(table_name)

          ALLOWED_ORIGIN = os.environ.get("ALLOWED_ORIGIN", "https://www.theprojectfolder.com")

          def lambda_handler(event, context):
              method = event.get("requestContext", {}).get("http", {}).get("method", "GET")
              
              cors_headers = {
                  "Content-Type": "application/json",
                  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
                  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
                  "Access-Control-Allow-Headers": "Content-Type"
              }
              
              if method == "OPTIONS":
                  return {
                      "statusCode": 200,
                      "headers": cors_headers,
                      "body": json.dumps({"message": "CORS preflight allowed"})
                  }
              
              if method == "POST":
                  try:
                      response = table.update_item(
                          Key={"visitor_count_id": "global"},
                          UpdateExpression="SET visitorCount = if_not_exists(visitorCount, :start) + :inc, #ts = :ts",
                          ExpressionAttributeValues={
                              ":inc": 1,
                              ":start": 0,
                              ":ts": str(datetime.utcnow())
                          },
                          ExpressionAttributeNames={
                              "#ts": "timestamp"
                          },
                          ReturnValues="UPDATED_NEW"
                      )
                      new_count = response["Attributes"]["visitorCount"]
                      return {
                          "statusCode": 200,
                          "headers": cors_headers,
                          "body": json.dumps({"visitorCount": int(new_count)})
                      }
                  except Exception as e:
                      print(f"[ERROR] POST failed: {str(e)}")
                      return {
                          "statusCode": 500,
                          "headers": cors_headers,
                          "body": json.dumps({"error": "Could not update visitor count"})
                      }
              
              elif method == "GET":
                  try:
                      response = table.get_item(Key={"visitor_count_id": "global"})
                      item = response.get("Item", {})
                      count = item.get("visitorCount", 0)
                      return {
                          "statusCode": 200,
                          "headers": cors_headers,
                          "body": json.dumps({"visitorCount": int(count)})
                      }
                  except Exception as e:
                      print(f"[ERROR] GET failed: {str(e)}")
                      return {
                          "statusCode": 500,
                          "headers": cors_headers,
                          "body": json.dumps({"error": "Could not retrieve visitor count"})
                      }
              
              else:
                  return {
                      "statusCode": 405,
                      "headers": cors_headers,
                      "body": json.dumps({"error": "Method Not Allowed"})
                  }
      Tags:
        - Key: Project
          Value: theprojectfolder
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Environment
          Value: prod

Outputs:
  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref VisitorCountTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt VisitorCounterFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref VisitorCounterFunction
    Export:
      Name: !Sub ${AWS::StackName}-FunctionName

  LambdaRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt VisitorCounterLambdaRole.Arn