name: Deploy Frontend Prod Stack

on:
  push:
     branches: [main]
     paths:
      - 'theprojectfolder/cloudresumechallenge/infrastructure/frontend-stack-prod.yaml'
      - '.github/workflows/deploy-prod-stack.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to CloudFormation (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for GitHub Actions (Prod)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::102587257710:role/GitHubActionsProdRole
          aws-region: us-east-1

      - name: Deploy frontend-stack-prod
        run: |
          aws cloudformation deploy \
            --stack-name frontend-stack-prod \
            --template-file ./theprojectfolder/cloudresumechallenge/infrastructure/frontend-stack-prod.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset