name: Test AWS OIDC & Permissions
on:
  workflow_dispatch:  # Manual trigger only, so you can run it safely anytime

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::102587257710:role/GitHubActionsProdRole
          aws-region: us-east-1

      - name: Confirm AWS Identity
        run: aws sts get-caller-identity

      - name: Verify S3 Access
        run: |
          echo "Listing S3 buckets to verify access..."
          aws s3 ls www.theprojectfolder.com || echo "❌ Failed: cannot list main bucket"
          aws s3 ls theprojectfolder.com || echo "⚠️ Root redirect bucket - read-only check"
          aws s3 ls my-site-access-logs || echo "⚠️ Logs bucket - read-only check"

      - name: Verify CloudFormation Access
        run: |
          echo "Checking CloudFormation stack access..."
          aws cloudformation describe-stacks --stack-name frontend-stack-prod || echo "❌ CloudFormation describe failed"

      - name: Verify CloudFront Permissions
        run: |
          echo "Checking CloudFront invalidation permissions..."
          aws cloudfront create-invalidation \
            --distribution-id E2UA1URROHIZXT \
            --paths "/test-verification-$(date +%s)" || echo "❌ CloudFront invalidation failed"
      
      - name: Verify Route53 Permissions
        run: |
          echo "Checking Route53 permissions..."
          aws route53 list-resource-record-sets --hosted-zone-id Z03024793FWW1BZ4QAAUV | head -n 5 || echo "❌ Route53 read failed"
