name: Test AWS OIDC Connection

on:
  workflow_dispatch:

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::102587257710:role/GitHubActionsProdRole
          aws-region: us-east-1
      - name: Verify OIDC connection
        run: aws sts get-caller-identity
